Repository vandermesis/Kolorofon, pull requests merged in 2020-01, with the labels that each got.

#8 Setup CI with GitHub Actions
  .swiftlint.yml
  Dangerfile
  Gemfile
  Gemfile.lock
  Mintfile
  bootstrap.sh
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Scanfile
Labels: enhancement

#10 Add cocoapods
  .github/workflows/ci.yml
  .gitignore
  .swiftlint.yml
  .travis.yml
  ColorPatterns.xcodeproj/project.pbxproj
  ColorPatterns.xcodeproj/xcshareddata/xcbaselines/BAC92D9122BA7B2B00D3B025.xcbaseline/028FBBEC-0975-4F5C-8E74-31C93F1676CA.plist
  ColorPatterns.xcodeproj/xcshareddata/xcbaselines/BAC92D9122BA7B2B00D3B025.xcbaseline/Info.plist
  ColorPatterns.xcworkspace/contents.xcworkspacedata
  ColorPatterns.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ColorPatterns/Controller/ViewController.swift
  ColorPatterns/Model/Colors.swift
  ColorPatterns/Model/GameTimer.swift
  ColorPatterns/Model/Sounds.swift
  ColorPatterns/Settings/SettingsBundleHelper.swift
  ColorPatterns/Support/AppDelegate.swift
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/1024.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/114.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/120.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/180.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/29.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/40.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/57.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/58.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/60.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/80.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/87.png
  ColorPatterns/Support/Assets.xcassets/AppIcon.appiconset/Contents.json
  ColorPatterns/Support/Assets.xcassets/Contents.json
  ColorPatterns/Support/Assets.xcassets/Logo_ver5.imageset/Contents.json
  ColorPatterns/Support/Assets.xcassets/Logo_ver5.imageset/Logo_ver5.png
  ColorPatterns/Support/Assets.xcassets/Logo_ver5.imageset/Logo_ver5@2x.png
  ColorPatterns/Support/Assets.xcassets/Logo_ver5.imageset/Logo_ver5@3x.png
  ColorPatterns/Support/Assets.xcassets/Startup/Contents.json
  ColorPatterns/Support/Base.lproj/LaunchScreen.storyboard
  ColorPatterns/Support/Info.plist
  ColorPatterns/Support/Sounds/note1.wav
  ColorPatterns/Support/Sounds/note2.wav
  ColorPatterns/Support/Sounds/note3.wav
  ColorPatterns/Support/Sounds/note4.wav
  ColorPatterns/Support/Sounds/note5.wav
  ColorPatterns/Support/Sounds/note6.wav
  ColorPatterns/Support/Sounds/note7.wav
  ColorPatterns/Support/UpdateColors.playground/Contents.swift
  ColorPatterns/Support/UpdateColors.playground/contents.xcplayground
  ColorPatternsTests/ColorPatternsTests.swift
  Dangerfile
  Gemfile
  Gemfile.lock
  Mintfile
  Podfile
  Podfile.lock
  README.md
  bootstrap.sh
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Scanfile
Labels: enhancement

#14 Update README.md
  README.md
Labels: documentation

#20 Code Review
  ColorPatterns.xcodeproj/project.pbxproj
  ColorPatterns/Extensions/Error+FriendlyMessage.swift
  ColorPatterns/Extensions/Int+StringConverter.swift
  ColorPatterns/Helpers/Constants.swift
  ColorPatterns/Helpers/SettingsBundleHelper.swift
  ColorPatterns/Helpers/SharedButton.swift
  ColorPatterns/Models/Score.swift
  ColorPatterns/Scenes/Game/GameController.swift
  ColorPatterns/Scenes/Game/GameController.xib
  ColorPatterns/Scenes/Game/GameCreator.swift
  ColorPatterns/Scenes/Game/GameEngine.swift
  ColorPatterns/Scenes/Game/GameSounds.swift
  ColorPatterns/Scenes/Game/GameTimer.swift
  ColorPatterns/Scenes/Game/GameViewModel.swift
  ColorPatterns/Scenes/GameOver/GameOverController.swift
  ColorPatterns/Scenes/GameOver/GameOverController.xib
  ColorPatterns/Scenes/GameOver/GameOverCreator.swift
  ColorPatterns/Scenes/StartMenu/StartMenuController.swift
  ColorPatterns/Scenes/StartMenu/StartMenuController.xib
  ColorPatterns/Scenes/StartMenu/StartMenuViewModel.swift
  ColorPatterns/Support/AppDelegate.swift
  ColorPatterns/Support/Assets.xcassets/Logo_ver5.imageset/Logo_ver5.png
  ColorPatterns/Support/Assets.xcassets/Logo_ver5.imageset/Logo_ver5@2x.png
  ColorPatterns/Support/Assets.xcassets/Logo_ver5.imageset/Logo_ver5@3x.png
  ColorPatterns/Support/Assets.xcassets/Logo_ver7.imageset/Contents.json
  ColorPatterns/Support/Assets.xcassets/Logo_ver7.imageset/Logo_ver7.png
  ColorPatterns/Support/Assets.xcassets/Logo_ver7.imageset/Logo_ver7@2x.png
  ColorPatterns/Support/Assets.xcassets/Logo_ver7.imageset/Logo_ver7@3x.png
  ColorPatterns/Support/Assets.xcassets/Startup/Contents.json
  ColorPatterns/Support/Base.lproj/LaunchScreen.storyboard
  ColorPatterns/Support/Colors.xcassets/backgroundPrimary.colorset/Contents.json
  ColorPatterns/Support/Colors.xcassets/backgroundSecondary.colorset/Contents.json
  ColorPatterns/Support/Colors.xcassets/buttonPrimary.colorset/Contents.json
  ColorPatterns/Support/Colors.xcassets/buttonSecondary.colorset/Contents.json
  ColorPatterns/Support/Colors.xcassets/buttonTertiary.colorset/Contents.json
  ColorPatterns/Support/Colors.xcassets/textPrimary.colorset/Contents.json
  ColorPatterns/Support/Colors.xcassets/textSecondary.colorset/Contents.json
  ColorPatterns/Support/Colors.xcassets/textTertiary.colorset/Contents.json
  ColorPatterns/Support/Localizable.strings
  ColorPatternsTests/ColorPatternsTests.swift
  ColorPatternsTests/Scenes/Game/FakeGameTimer.swift
  ColorPatternsTests/Scenes/Game/GameTimerTests.swift
  ColorPatternsTests/Scenes/Game/GameViewModelTests.swift
  ColorPatternsTests/Scenes/GameOver/GameOverCreatorTests.swift
  ColorPatternsTests/Scenes/StartMenu/StartMenuViewModelTests.swift
Labels: bug

#21 Add animation to StartMenu
  ColorPatterns.xcodeproj/project.pbxproj
  ColorPatterns/Helpers/SharedButton.swift
  ColorPatterns/Scenes/StartMenu/StartMenuController.swift
  ColorPatterns/Scenes/StartMenu/StartMenuController.xib
  ColorPatterns/Support/Colors.xcassets/buttonSecondary.colorset/Contents.json
  ColorPatterns/Support/Colors.xcassets/textTertiary.colorset/Contents.json
  ColorPatterns/Support/LottieAnimations/990-inattentive.json
Labels: enhancement
